name: master_brain
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.35
  get: ^4.6.6
  flutter_svg: ^2.0.9
  soundpool: ^2.4.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter_gen:
  assets:
    # Optional
    enabled: true
    package_parameter_enabled: false
    # Optional
    # Avaliable values:
    # - camel-case
    # - snake-case
    # - dot-delimiter
    style: dot-delimiter
  output: lib/gen/ # Optional (default: lib/gen/)
    # style: snake-case                                                                       │
    # package_parameter_enabled: true 
  line_length: 80 # Optional (default: 80)
  null_safety: true
  # Optional
  integrations:
    flutter_svg: true

# Run "flutter pub run flutter_launcher_icons:main" to create App Icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/sounds/

  fonts:
    - family: Sansita
      fonts:
        - asset: assets/fonts/Sansita-Bold.ttf
    - family: RubikMonoOne
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
